# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:

      # specify the version you desire here
      - image: circleci/node:10.15.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Check dist
          command: ls -la dist

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
              - .
      # run tests!
      #- run: yarn test

  deploy:
      working_directory: ~/workspace
      docker:
          - image: circleci/node:10.15.3
      steps:
          - attach_workspace:
              at: .
          - run: git checkout git@github.com:hondasports/hondasports.github.io.git
          - run: git config user.email "hondasports+circleci@users.noreply.github.com"
          - run: git config user.name "yousan+circleci"
          - command: cp -r dist/* hondasports.github.io/.
          - run: git add hondasports.github.io
          - run: git commit -m 'auto commit by cicleCI'
          - run: git push origin master

workflows:
    version: 2
    build_and_deploy:
        jobs:
            filters:
                branches:
                only: master
            - build
            # - deploy:
            #     requires:
            #         - build
