# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:

      # specify the version you desire here
      - image: circleci/node:10.15.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Check dist
          command: ls -la dist

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
              - .
      # run tests!
      #- run: yarn test

  deploy:
      working_directory: ~/workspace
      docker:
          - image: circleci/node:10.15.3
      steps:
          - attach_workspace:
              at: .
          - run:
              name: push to githubio
              command: |
                mkdir -p ~/.ssh
                ssh-keyscan github.com >> ~/.ssh/known_hosts
                git clone git@github.com:hondasports/hondasports.github.io.git
                git config user.email "circleci+mysite@noreply.github.com"
                git config user.name "Circleci"
                cd hondasports.github.io
                git rm -r ./*
                cp -r ~/workspace/dist/* .
                git add * ./*
                git commit -m 'auto commit by CicleCI'
                git push origin master

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
